alias: Electricity rate
description: Sets electricity rate between peak, offpeak and shoulder
trigger:
  - platform: time_pattern
    hours: /1
  - platform: homeassistant
    event: start
condition: []
action:
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ now().month in (1,2,3,11,12) and now().weekday() in (0,1,2,3,4)
              and now().hour >= 14 and now().hour < 20 }}
        sequence:
          - service: input_select.select_option
            data:
              option: peak
            target:
              entity_id: input_select.electricity_rate
          - service: input_boolean.turn_on
            entity_id: input_boolean.electricity_rate_peak
      - conditions:
          - condition: template
            value_template: >-
              {{ now().month in (6,7,8) and now().weekday() in (0,1,2,3,4) and
              now().hour >= 17 and now().hour < 21 }}
        sequence:
          - service: input_select.select_option
            data:
              option: peak
            target:
              entity_id: input_select.electricity_rate
          - service: input_boolean.turn_on
            entity_id: input_boolean.electricity_rate_peak
      - conditions:
          - condition: template
            value_template: >-
              {{ now().weekday() in (5,6) and now().hour >= 7 and now().hour <
              22 }}
        sequence:
          - service: input_select.select_option
            data:
              option: shoulder
            target:
              entity_id: input_select.electricity_rate
          - service: input_boolean.turn_off
            entity_id: input_boolean.electricity_rate_peak
      - conditions:
          - condition: template
            value_template: >-
              {{ now().month in (1,2,3,11,12) and now().weekday() in (0,1,2,3,4)
              and now().hour in (7,8,9,10,11,12,13,14,20,21) }}
        sequence:
          - service: input_select.select_option
            data:
              option: shoulder
            target:
              entity_id: input_select.electricity_rate
          - service: input_boolean.turn_off
            entity_id: input_boolean.electricity_rate_peak
      - conditions:
          - condition: template
            value_template: >-
              {{ now().month in (6,7,8) and now().weekday() in (0,1,2,3,4) and
              now().hour in (7,8,9,10,11,12,13,14,15,16,17,21,22) }}
        sequence:
          - service: input_select.select_option
            data:
              option: shoulder
            target:
              entity_id: input_select.electricity_rate
          - service: input_boolean.turn_off
            entity_id: input_boolean.electricity_rate_peak
      - conditions:
          - condition: template
            value_template: >-
              {{ now().month in (4,5,9,10) and now().weekday() in (0,1,2,3,4)
              and now().hour >= 7 and now().hour < 22 }}
        sequence:
          - service: input_select.select_option
            data:
              option: shoulder
            target:
              entity_id: input_select.electricity_rate
          - service: input_boolean.turn_off
            entity_id: input_boolean.electricity_rate_peak
    default:
      - service: input_select.select_option
        data:
          option: offpeak
        target:
          entity_id: input_select.electricity_rate
      - service: input_boolean.turn_off
        entity_id: input_boolean.electricity_rate_peak
mode: single
