blueprint:
  name: AREA set natural light
  description: Set natural light in an area.
  domain: automation
  source_url: https://github.com/konstar/hass/blob/main/blueprints/area-set-natural-light.yaml
  input:
    artifical_light_source:
      name: Artifical light source
      description: Main source of artifical light. E.g. Ceiling lights.
      selector:
        entity:
          domain: light
    natural_light_helper:
      name: Natural light helper 
      description: Helper that sets the boolean state of natural light.
      selector:
        entity:
          domain: input_boolean
    light_sensor:
      name: Light sensor
      description: The sensor that measures light in lux.
      selector:
        entity:
          domain: sensor
          device_class: illuminance
trigger:
  - platform: state
    entity_id:
      - sun.sun
      - input_number.artificial_light_on
      - input_number.artificial_light_off
      - !input artifical_light_source
      - !input light_sensor
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: sun.sun
            state: below_horizon
        sequence:
          - service: input_boolean.turn_off
            entity_id: !input natural_light_helper
      - conditions:
          - condition: state
            entity_id: sun.sun
            state: above_horizon
          - condition: state
            entity_id: !input artifical_light_source
            state: 'off'
          - condition: numeric_state
            entity_id: !input light_sensor
            above: '0'
            value_template: "{{ state.state|int - states('!input input_number.artificial_light_on')|int }}"
        sequence:
          - service: input_boolean.turn_on
            entity_id: !input natural_light_helper
      - conditions:
          - condition: state
            entity_id: sun.sun
            state: above_horizon
          - condition: state
            entity_id: !input artifical_light_source
            state: 'on'
          - condition: numeric_state
            entity_id: !input light_sensor
            above: '0'
            value_template: "{{ state.state|int - states('!input input_number.artificial_light_off')|int }}"
        sequence:
          - service: input_boolean.turn_on
            entity_id: !input natural_light_helper
    default: []
mode: single
