blueprint:
  name: AREA set temperature
  description: Set temperature selection for the state of an area.
  domain: automation
  source_url: https://github.com/konstar/hass/blob/main/blueprints/area-set-temperature.yaml
  input:
    output:
      name: Output helper
      description: Helper to store the human temeperature of the area.
      selector:
        entity:
          domain: input_select
    sensor:
      name: Temperature Sensor
      description: Temperature sensor of the area.
      selector:
        entity:
          domain: sensor
          device_class: temperature
    sleep:
      name: Sleep helper
      description: Helper boolean that captures whether someone is sleeping in the area.
      selector:
        entity:
          domain: input_boolean
    active_temp:
      name: Active temperature helper
      description: Helper with the normal temperature of the area in degc.
      selector:
        entity:
          domain: input_number
    sleep_temp:
      name: Sleep temperature helper
      description: Helper with the normal temperature of the area in degc.
      selector:
        entity:
          domain: input_number
trigger:
  - id: active_normal
    platform: template
    value_template: >-
      {% if is_state('!input sleep','off')
        and ( states('!input sensor')|float - states('!input active_temp')|float ) > -2
        and ( states('!input sensor')|float - states('!input active_temp')|float ) < 2 -%}
        true
      {%- else -%}
        false
      {%- endif %}
    for: '00:05:00'
  - id: sleep_normal
    platform: template
    value_template: >-
      {% if is_state('!input sleep','on')
        and ( states('!input sensor')|float - states('!input sleep_temp')|float ) > -2
        and ( states('!input sensor')|float - states('!input sleep_temp')|float ) < 2 -%}
        true
      {%- else -%}
        false
      {%- endif %}
    for: '00:05:00'
  - id: active_hot
    platform: template
    value_template: >-
      {% if is_state('!input sleep','off')
        and ( states('!input sensor')|float - states('!input active_temp')|float ) > 2
        and ( states('!input sensor')|float - states('!input active_temp')|float ) < 4 -%}
        true
      {%- else -%}
        false
      {%- endif %}
    for: '00:05:00'
  - id: sleep_hot
    platform: template
    value_template: >-
      {% if is_state('!input sleep','on')
        and ( states('!input sensor')|float - states('!input sleep_temp')|float ) > 2
        and ( states('!input sensor')|float - states('!input sleep_temp')|float ) < 4 -%}
        true
      {%- else -%}
        false
      {%- endif %}
    for: '00:05:00'
  - id: active_cold
    platform: template
    value_template: >-
      {% if is_state('!input sleep','off')
        and ( states('!input sensor')|float - states('!input active_temp')|float ) > -4
        and ( states('!input sensor')|float - states('!input active_temp')|float ) < -2 -%}
        true
      {%- else -%}
        false
      {%- endif %}
    for: '00:05:00'
  - id: sleep_cold
    platform: template
    value_template: >-
      {% if is_state('!input sleep','on')
        and ( states('!input sensor')|float - states('!input sleep_temp')|float ) > -4
        and ( states('!input sensor')|float - states('!input sleep_temp')|float ) < -2 -%}
        true
      {%- else -%}
        false
      {%- endif %}
    for: '00:05:00'
  - id: active_very_hot
    platform: template
    value_template: >-
      {% if is_state('!input sleep','off')
        and ( states('!input sensor')|float - states('!input active_temp')|float ) > 4 -%}
        true
      {%- else -%}
        false
      {%- endif %}
    for: '00:05:00'
  - id: sleep_very_hot
    platform: template
    value_template: >-
      {% if is_state('!input sleep','on')
        and ( states('!input sensor')|float - states('!input sleep_temp')|float ) > 4 -%}
        true
      {%- else -%}
        false
      {%- endif %}
    for: '00:05:00'
  - id: active_very_cold
    platform: template
    value_template: >-
      {% if is_state('!input sleep','off')
        and ( states('!input sensor')|float - states('!input active_temp')|float ) < -4 -%}
        true
      {%- else -%}
        false
      {%- endif %}
    for: '00:05:00'
  - id: sleep_very_cold
    platform: template
    value_template: >-
      {% if is_state('!input sleep','on')
        and ( states('!input sensor')|float - states('!input sleep_temp')|float ) < -4 -%}
        true
      {%- else -%}
        false
      {%- endif %}
    for: '00:05:00'
  - id: unknown_1
    platform: numeric_state
    entity_id: !input sensor
    below: 1
    for: 00:05:00
  - id: unknown_2
    platform: numeric_state
    entity_id: !input sensor
    above: 50
    for: 00:05:00
condition: []
action:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: active_normal
              - condition: trigger
                id: sleep_normal
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input output
            data:
              option: "normal"
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: active_hot
              - condition: trigger
                id: sleep_hot
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input output
            data:
              option: "hot"
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: active_cold
              - condition: trigger
                id: sleep_cold
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input output
            data:
              option: "cold"
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: active_very_hot
              - condition: trigger
                id: sleep_very_hot
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input output
            data:
              option: "very_hot"
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: active_very_cold
              - condition: trigger
                id: sleep_very_cold
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input output
            data:
              option: "very-cold"
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: unknown_1
              - condition: trigger
                id: unknown_2
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input output
            data:
              option: "unknown"
mode: single
