blueprint:
  name: AREA set natural light
  description: Figure out whether there is sufficient natural light in a room, which will eventually trigger artificial light to be switched on or off automatically
  domain: automation
  source_url: https://github.com/konstar/hass/blob/main/blueprints/area-set-natural-light.yaml
  input:
    artifical_light_source:
      name: Artifical light source
      description: Main source(s) of artifical light. E.g. Ceiling lights and Ceiling Fan light
      selector:
        entity:
          domain: light
          multiple: true
    natural_light_helper:
      name: Natural light helper 
      description: Helper that sets the boolean state of natural light.
      selector:
        entity:
          domain: input_boolean
    light_sensor:
      name: Light sensor
      description: The sensor that measures light in lux.
      selector:
        entity:
          domain: sensor
          device_class: illuminance
    artifical_light_on:
      name: Artificial light on helper
      description: Helper which records the lux level to switch artificial light on, i.e. The level while artifical light is off and only natural light is present.
      selector:
        entity:
          domain: input_number
    artifical_light_off:
      name: Artificial light off helper
      description: Helper which records the lux level to switch artificial light off, i.e. The level while artifical light on, so it needs to consider the lux level while there is both natural and artifical light.
      selector:
        entity:
          domain: input_number
variables:
  artifical_light_source: !input artifical_light_source
  natural_light_helper: !input natural_light_helper
  light_sensor: !input light_sensor
  artifical_light_on: !input artifical_light_on
  artifical_light_off: !input artifical_light_off
trigger:
  - platform: state
    entity_id:
      - sun.sun
      - !input artifical_light_on
      - !input artifical_light_off
      - !input light_sensor
  - platform: state
    entity_id: !input artifical_light_source
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: sun.sun
            state: below_horizon
        sequence:
          - service: input_boolean.turn_off
            entity_id: !input natural_light_helper
      - conditions:
          - condition: state
            entity_id: sun.sun
            state: above_horizon
          - condition: state
            entity_id: !input artifical_light_source
            state: 'off'
          - condition: numeric_state
            entity_id: !input light_sensor
            above: '5'
            value_template: "{{ state.state|int - states(artifical_light_on)|int }}"
        sequence:
          - service: input_boolean.turn_on
            entity_id: !input natural_light_helper
      - conditions:
          - condition: state
            entity_id: sun.sun
            state: above_horizon
          - condition: state
            entity_id: !input artifical_light_source
            state: 'off'
          - condition: numeric_state
            entity_id: !input light_sensor
            below: '-5'
            value_template: "{{ state.state|int - states(artifical_light_on)|int }}"
        sequence:
          - service: input_boolean.turn_off
            entity_id: !input natural_light_helper
      - conditions:
          - condition: state
            entity_id: sun.sun
            state: above_horizon
          - condition: state
            entity_id: !input artifical_light_source
            state: 'on'
            match: any
          - condition: numeric_state
            entity_id: !input light_sensor
            above: '5'
            value_template: "{{ state.state|int - states(artifical_light_off)|int }}"
        sequence:
          - service: input_boolean.turn_on
            entity_id: !input natural_light_helper
      - conditions:
          - condition: state
            entity_id: sun.sun
            state: above_horizon
          - condition: state
            entity_id: !input artifical_light_source
            state: 'on'
            match: any
          - condition: numeric_state
            entity_id: !input light_sensor
            below: '-5'
            value_template: "{{ state.state|int - states(artifical_light_off)|int }}"
        sequence:
          - service: input_boolean.turn_off
            entity_id: !input natural_light_helper
    default: []
mode: restart