blueprint:
  name: AREA set humidity
  description: Set humidity selection for the state of an area.
  domain: automation
  source_url: https://github.com/konstar/hass/blob/main/blueprints/area-set-humidity.yaml
  input:
    area:
      name: Area input helper
      description: Dropdown helper associated with the humidity of an area.
      selector:
        entity:
          domain: input_select
    sensor:
      name: Humidity Sensor
      description: Humidity sensor of the area
      selector:
        entity:
          domain: sensor
          device_class: humidity
trigger:
  - platform: state
    entity_id: !input sensor
    state: 0
    for: 00:05:00
  - platform: numeric_state
    entity_id: !input sensor
    above: input_number.home_healthy_humidity_max
    for: 00:05:00
  - platform: numeric_state
    entity_id: !input sensor
    below: input_number.home_healthy_humidity_max
    above: input_number.home_ideal_humidity_max
    for: 00:05:00
  - platform: numeric_state
    entity_id: !input sensor
    below: input_number.home_ideal_humidity_max
    above: input_number.home_ideal_humidity_min
    for: 00:05:00
  - platform: numeric_state
    entity_id: !input sensor
    below: input_number.home_ideal_humidity_min
    above: input_number.home_healthy_humidity_min
    for: 00:05:00
  - platform: numeric_state
    entity_id: !input sensor
    below: input_number.home_healthy_humidity_min
    for: 00:05:00
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input sensor
            state: 0
        sequence:
          - service: input_number.set_option
            entity_id: !input area
            data:
              option: "unknown"
      - conditions:
          - condition: numeric_state
            entity_id: !input sensor
            above: input_number.home_healthy_humidity_max
        sequence:
          - service: input_number.set_option
            entity_id: !input area
            data:
              option: "very-humid"
      - conditions:
          - condition: numeric_state
            entity_id: !input sensor
            below: input_number.home_healthy_humidity_max
            above: input_number.home_ideal_humidity_max
        sequence:
          - service: input_number.set_option
            entity_id: !input area
            data:
              option: "humid"
      - conditions:
          - condition: numeric_state
            entity_id: !input sensor
            below: input_number.home_ideal_humidity_max
            above: input_number.home_ideal_humidity_min
        sequence:
          - service: input_number.set_option
            entity_id: !input area
            data:
              option: "normal"
      - conditions:
          - condition: numeric_state
            entity_id: !input sensor
            below: input_number.home_ideal_humidity_min
            above: input_number.home_healthy_humidity_min
        sequence:
          - service: input_number.set_option
            entity_id: !input area
            data:
              option: "dry"
      - conditions:
          - condition: numeric_state
            entity_id: !input sensor
            below: input_number.home_healthy_humidity_min
        sequence:
          - service: input_number.set_option
            entity_id: !input area
            data:
              option: "very-dry"
mode: single
