blueprint:
  name: DEVICE Echo
  description: Manages an Amazon Echo device
  domain: automation
  source_url: https://github.com/konstar/hass/blob/main/blueprints/DEVICE-Echo.yaml
  input:
    time:
      name: Time selector
      description: Time selector of the room
      selector:
        entity:
          domain: input_select
    door:
      name: Door
      description: Door sensor for the room
      selector:
        entity:
          domain: binary_sensor
          device_class: door
    activity:
      name: Activity Helper
      description: Activity helper of the room
      selector:
        entity:
          domain: input_select
    presence:
      name: Presence Helper
      description: Presence helper of the room
      selector:
        entity:
          domain: input_select
    humidity:
      name: Humidity Helper
      description: Humidity helper of the room
      selector:
        entity:
          domain: input_select
    temperature:
      name: Temperature Helper
      description: Temperature helper of the room
      selector:
        entity:
          domain: input_select
    temperature_sensor:
      name: Temperature Sensor
      description: Temperature sensor of the room
      selector:
        entity:
          domain: sensor
          device_class: temperature
    temperature_target:
      name: Temperature Target Helper
      description: Target temperature helper of the room
      selector:
        entity:
          domain: input_number
variables:
  air_con: !input air_con
  door: !input door
  activity: !input activity
  presence: !input presence
  humidity: !input humidity
  temperature: !input temperature
  temperature_sensor: !input temperature_sensor
  temperature_target: !input temperature_target
trigger:
  - platform: state
    entity_id: !input presence
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: input_boolean.lounge_presence
            state: "on"
        sequence:
          - service: media_player.volume_mute
            data:
              is_volume_muted: false
            entity_id:
              - media_player.lounge_speakers
              - media_player.lounge_echo_1
              - media_player.lounge_echo_2
          - service: switch.turn_off
            entity_id:
              - switch.lounge_speakers_do_not_disturb_switch
              - switch.lounge_echo_1_do_not_disturb_switch
              - switch.lounge_echo_2_do_not_disturb_switch
    default:
      - service: media_player.volume_mute
        data:
          is_volume_muted: true
        entity_id:
          - media_player.lounge_speakers
          - media_player.lounge_echo_1
          - media_player.lounge_echo_2
      - service: switch.turn_on
        entity_id:
          - switch.lounge_speakers_do_not_disturb_switch
          - switch.lounge_echo_1_do_not_disturb_switch
          - switch.lounge_echo_2_do_not_disturb_switch
  - choose:
      - conditions:
          - condition: state
            entity_id: input_boolean.lounge_presence
            state: "on"
          - condition: state
            entity_id: input_select.lounge_time
            state: daytime
        sequence:
          - service: media_player.volume_set
            entity_id:
              - media_player.lounge_speakers
              - media_player.lounge_echo_1
              - media_player.lounge_echo_2
            data:
              volume_level: 0.5
      - conditions:
          - condition: state
            entity_id: input_boolean.lounge_presence
            state: "on"
          - condition: state
            entity_id: input_select.lounge_time
            state: evening
        sequence:
          - service: media_player.volume_set
            entity_id:
              - media_player.lounge_speakers
              - media_player.lounge_echo_1
              - media_player.lounge_echo_2
            data:
              volume_level: 0.3
      - conditions:
          - condition: state
            entity_id: input_boolean.lounge_presence
            state: "on"
          - condition: state
            entity_id: input_select.lounge_time
            state: midnight
        sequence:
          - service: media_player.volume_set
            entity_id:
              - media_player.lounge_speakers
              - media_player.lounge_echo_1
              - media_player.lounge_echo_2
            data:
              volume_level: 0.2
    default: []
mode: single
