blueprint:
  name: AREA set media
  description: Set media player in an area to recieve announcements, play music or sleep.
  domain: automation
  source_url: https://github.com/konstar/hass/blob/main/blueprints/area-set-media.yaml
  input:
    area_activity:
      name: Area input helper for activity
      description: Dropdown helper that describes the activity in an area.
      selector:
        entity:
          domain: input_select
    area_time:
      name: Area input helper for time
      description: Dropdown helper that describes the time of day in an area.
      selector:
        entity:
          domain: input_select
    do_not_disturb_switch:
      name: Media Player do not disturb switch
      description: Alexa uses a switch to turn the Echo device between do not disturb mode
      selector:
        entity:
          domain: switch
    media_player:
      name: Media player device
      description: Device to control
      selector:
        entity:
          domain: media_player
    active_volume:
      name: Active area device volume 
      description: Volume of the media player while in an active area.
      default: 0.3
      selector:
        number:
          min: 0
          max: 1
          step: 0.1
          mode: slider
    relaxed_volume:
      name: Relaxed area device volume
      description: Volume of the media player while in an area with people relaxing.
      default: 0.2
      selector:
        number:
          min: 0
          max: 1
          step: 0.1
          mode: slider
    focused_volume:
      name: Focused area device volume
      description: Volume of the media player while in a area with focused people.
      default: 0.1
      selector:
        number:
          min: 0
          max: 1
          step: 0.1
          mode: slider
trigger:
  - platform: state
    entity_id: !input area_time
  - platform: state
    entity_id: !input area_activity
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input area_activity
            state: active
        sequence:
          - service: switch.turn_off
            entity_id: !input do_not_disturb_switch
          - service: media_player.volume_mute
            data:
              is_volume_muted: false
            entity_id: !input media_player
          - service: media_player.volume_set
            entity_id: !input media_player
            data:
              volume_level: !input active_volume
      - conditions:
          - condition: state
            entity_id: !input area_activity
            state: relax
        sequence:
          - service: switch.turn_off
            entity_id: !input do_not_disturb_switch
          - service: media_player.volume_mute
            data:
              is_volume_muted: false
            entity_id: !input media_player
          - service: media_player.volume_set
            entity_id: !input media_player
            data:
              volume_level: !input relaxed_volume
      - conditions:
          - condition: state
            entity_id: !input area_activity
            state: focus
        sequence:
          - service: switch.turn_off
            entity_id: !input do_not_disturb_switch
          - service: media_player.volume_mute
            data:
              is_volume_muted: false
            entity_id: !input media_player
          - service: media_player.volume_set
            entity_id: !input media_player
            data:
              volume_level: !input focused_volume
    default:
      - service: media_player.media_stop
        entity_id: !input media_player
      - service: media_player.volume_mute
        entity_id: !input media_player
        data:
          is_volume_muted: true
      - service: switch.turn_on
        entity_id: !input do_not_disturb_switch
mode: single
