blueprint:
  name: AREA set groups (green)
  description: Set entities within area based groups.
  domain: automation
  source_url: https://github.com/konstar/hass/blob/main/blueprints/AREA-set-groups-blue.yaml
  input:
    area:
      name: Area
      description: Name of the Area this blueprint is for. E.g. "Deck"
      selector:
        text:
variables:
  area: !input "area"
trigger:
  - platform: time_pattern
    hours: /1
  - platform: homeassistant
    event: start
  - platform: event
    event_type: call_service
    event_data:
      domain: group
      service: reload
condition: []
action:
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: group.set
    data:
      object_id: "{{ area|lower|replace(' ','_') }}_humidity"
      entities: >-
        {% set entities = expand(area_entities(area))
        | selectattr('domain','eq','sensor')
        | selectattr('attributes.device_class','defined')
        | selectattr('attributes.device_class','eq','humidity')
        | selectattr('attributes.unit_of_measurement','eq','%')
        | select('ne','0')
        | map(attribute='entity_id') | list %}
        {% if entities|count > 0 %}
          {{ entities|join(',') }}
        {% else %}[]{% endif %}
  - service: group.set
    data:
      object_id: "{{ area|lower|replace(' ','_') }}_illuminance"
      entities: >-
        {% set entities = expand(area_entities(area))
        | selectattr('domain','eq','sensor')
        | selectattr('attributes.device_class','defined')
        | selectattr('attributes.device_class','eq','illuminance')
        | selectattr('attributes.unit_of_measurement','eq','lx')
        | rejectattr('entity_id','match','.*_mi_.*')
        | map(attribute='entity_id') | list %}
        {% if entities|count > 0 %}
          {{ entities|join(',') }}
        {% else %}[]{% endif %}
  - service: group.set
    data:
      object_id: "{{ area|lower|replace(' ','_') }}_motion"
      entities: >-
        {% set entities = expand(area_entities(area))
        | selectattr('domain','eq','binary_sensor')
        | selectattr('attributes.device_class','defined')
        | selectattr('attributes.device_class','match','motion|moving|occupancy|presence')
        | selectattr('entity_id','match','.*_occupancy')
        | map(attribute='entity_id') | list %}
        {% if entities|count > 0 %}
          {{ entities|join(',') }}
        {% else %}[]{% endif %}
  - service: group.set
    data:
      object_id: "{{ area|lower|replace(' ','_') }}_temperature"
      entities: >-
        {% set entities = expand(area_entities(area))
        | selectattr('domain','eq','sensor')
        | selectattr('attributes.device_class','defined')
        | selectattr('attributes.device_class','eq','temperature')
        | selectattr('attributes.unit_of_measurement','eq','°C')
        | select('ne','0')
        | rejectattr('entity_id','match','.*_feels_like|.*_plug_temperature|.*_device_temperature|.*_bed_temperature')
        | map(attribute='entity_id') | list %}
        {% if entities|count > 0 %}
          {{ entities|join(',') }}
        {% else %}[]{% endif %}
mode: single
