blueprint:
  name: AREA set 2 state presence
  description: Set presence selection for the state of an area.
  domain: automation
  source_url: https://github.com/konstar/hass/blob/main/blueprints/area-set-2-state-presence.yaml
  input:
    always_present_entity:
      name: Entity always present
      description: Entity which if active is always present. E.g. Sleep boolean
      selector:
        entity:
    always_present_state:
      name: State always present
      description: State of the entity which signifies active. E.g. "on" for Sleep boolean
      selector:
        entity:
    presence_:
      name: Presence helper
      description: Helper that records whether there is someone present in the room or not (4 states).
      selector:
        entity:
          domain: input_select
    enter_timeout:
      name: Enter timeout
      description: Duration in seconds until room is marked as present or absent.
      default: 120
      selector:
        number:
          min: 0
          max: 600
          unit_of_measurement: "seconds"
    present_timeout:
      name: Enter timeout
      description: Duration in seconds until room is marked as left if there has been no motion.
      default: 900
      selector:
        number:
          min: 0
          max: 1800
          unit_of_measurement: "seconds"
    leave_timeout:
      name: Enter timeout
      description: Duration in seconds until room is marked as absent if there has been no motion.
      default: 120
      selector:
        number:
          min: 0
          max: 600
          unit_of_measurement: "seconds"
variables:
  motion_sensor: !input "motion_sensor"
  sleep_helper: !input "sleep_helper"
  presence_output: !input "presence_output"
trigger:
  - platform: state
    entity_id: !input "motion_sensor"
    to: "on"
    id: motion
  - platform: state
    entity_id: !input "motion_sensor"
    to: "off"
    for: !input "present_timeout"
    id: no_motion
  - platform: state
    entity_id: !input "presence_output"
    to: enter
    for: !input "enter_timeout"
    id: maybe_stay_room
  - platform: state
    entity_id: !input "presence_output"
    to: leave
    for: !input "leave_timeout"
    id: maybe_left_room
  - platform: state
    entity_id: !input "sleep_helper"
    to: "on"
    id: sleep_on
  - platform: state
    entity_id: !input "sleep_helper"
    to: "off"
    id: sleep_off
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input "sleep_helper"
            state: "on"
        sequence:
          - service: input_boolean.turn_on
            entity_id: input_boolean.master_bedroom_occupied
          - service: input_select.select_option
            target:
              entity_id: !input "presence_output"
            data:
              option: present
      - conditions:
          - condition: trigger
            id: motion
          - condition: or
            conditions:
              - condition: state
                entity_id: !input "presence_output"
                state: unknown
              - condition: state
                entity_id: !input "presence_output"
                state: absent
        sequence:
          - service: input_boolean.turn_on
            entity_id: input_boolean.master_bedroom_occupied
          - service: input_select.select_option
            target:
              entity_id: !input "presence_output"
            data:
              option: enter
      - conditions:
          - condition: trigger
            id: maybe_stay_room
          - condition: state
            entity_id: !input "motion_sensor"
            state: "on"
        sequence:
          - service: input_boolean.turn_on
            entity_id: input_boolean.master_bedroom_occupied
          - service: input_select.select_option
            target:
              entity_id: !input "presence_output"
            data:
              option: present
      - conditions:
          - condition: trigger
            id: maybe_stay_room
          - condition: state
            entity_id: !input "motion_sensor"
            state: "off"
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.master_bedroom_occupied
          - service: input_select.select_option
            target:
              entity_id: !input "presence_output"
            data:
              option: absent
      - conditions:
          - condition: trigger
            id: left_room
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.master_bedroom_occupied
          - service: input_select.select_option
            target:
              entity_id: !input "presence_output"
            data:
              option: absent
      - conditions:
          - condition: state
            entity_id: !input "presence_output"
            state: leave
          - condition: state
            entity_id: !input "motion_sensor"
            state: "off"
            for: 00:02:00
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.master_bedroom_occupied
          - service: input_select.select_option
            target:
              entity_id: !input "presence_output"
            data:
              option: absent
      - conditions:
          - condition: state
            entity_id: !input "presence_output"
            state: leave
          - condition: state
            entity_id: !input "motion_sensor"
            state: "on"
        sequence:
          - service: input_boolean.turn_on
            entity_id: input_boolean.master_bedroom_occupied
          - service: input_select.select_option
            target:
              entity_id: !input "presence_output"
            data:
              option: present
      - conditions:
          - condition: trigger
            id: no_motion
          - condition: state
            entity_id: !input "presence_output"
            state: present
        sequence:
          - service: input_boolean.turn_on
            entity_id: input_boolean.master_bedroom_occupied
          - service: input_select.select_option
            target:
              entity_id: !input "presence_output"
            data:
              option: leave
mode: single
