blueprint:
  name: DEVICE Media Player
  description: Manage 1 or many media player devices.
    Comma separate multiple values, to specify when devices should be set, e.g. sleep,work,midnight,absent
  domain: automation
  source_url: https://github.com/konstar/hass/blob/main/blueprints/DEVICE-Media-Player.yaml
  input:
    devices:
      name: Media device(s)
      description: Devices that this blueprint will apply to
      selector:
        entity:
          domain: media_player
          multiple: true
    activity:
      name: Activity helper
      description: Activity helper of the room
      selector:
        entity:
          domain: input_select
    presence:
      name: Presence helper
      description: Presence helper of the room
      selector:
        entity:
          domain: input_select
    time:
      name: Time helper
      description: Time selector of the room
      selector:
        entity:
          domain: input_select
    dnd:
      name: DND
      description: When should devices be set to Do Not Disturb mode?
      selector:
        text:
          type: text
    mute:
      name: Mute
      description: Which should device be muted?
      selector:
        text:
          type: text
    pct10:
      name: 10% volume
      description: When should the device be set to 10% volume?
      selector:
        text:
          type: text
    pct20:
      name: 20% volume
      description: When should the device be set to 20% volume?
      selector:
        text:
          type: text
    pct30:
      name: 30% volume
      description: When should the device be set to 30% volume?
      selector:
        text:
          type: text
    pct40:
      name: 40% volume
      description: When should the device be set to 40% volume?
      selector:
        text:
          type: text
    pct50:
      name: 50% volume
      description: When should the device be set to 50% volume?
      selector:
        text:
          type: text
variables:
  devices: !input devices
  devices_dnd: >-
    {{ devices
    | map('regex_replace','$','_do_not_disturb')
    | list
    | replace('media_player','switch')
    }}
  activity: !input activity
  activity_states: "{{ states[activity].state }}"
  presence: !input presence
  time: !input time
# Keeping this here for now as I had to go through a lot of pain to figure this out
#  entity_states: >-
#    {{ [states[activity],states[presence],states[time]]
#    | map(attribute='state') }}
  dnd: !input dnd
  mute: !input mute
  pct10: !input pct10
  pct20: !input pct20
  pct30: !input pct30
  pct40: !input pct40
  pct50: !input pct50
trigger:
  - platform: state
    entity_id:
      - !input activity
      - !input presence
      - !input time
condition: []
action:
  - if:
      - or:
          - "{{ activity_states in dnd }}"
          - "{{ presence_states in dnd }}"
          - "{{ time_states     in dnd }}"
    then:
      - if:
          - condition: state
            entity_id: "{{ devices_dnd }}"
            state: "off"
        then:
          - service: switch.turn_on
            target:
              entity_id: "{{ devices_dnd }}"
    else:
      - if:
          - condition: state
            entity_id: "{{ devices_dnd }}"
            state: "on"
        then:
          - service: switch.turn_off
            target:
              entity_id: "{{ devices_dnd }}"
  - choose:
      - conditions:
          - or:
              - "{{ activity_states in mute }}"
              - "{{ presence_states in mute }}"
              - "{{ time_states     in mute }}"
        sequence:
          - if:
              - not:
                  - condition: state
                    entity_id: !input devices
                    attribute: is_volume_muted
                    state: true
            then:
              - service: media_player.volume_mute
                entity_id: !input devices
                data:
                  is_volume_muted: true
      - conditions:
          - or:
              - "{{ activity_states in pct10 }}"
              - "{{ presence_states in pct10 }}"
              - "{{ time_states     in pct10 }}"
        sequence:
          - if:
              - not:
                  - condition: state
                    entity_id: !input devices
                    attribute: volume_level
                    state: 0.1
            then:
              - service: media_player.volume_set
                entity_id: !input devices
                data:
                  volume_level: 0.1
      - conditions:
          - or:
              - "{{ activity_states in pct20 }}"
              - "{{ presence_states in pct20 }}"
              - "{{ time_states     in pct20 }}"
        sequence:
          - if:
              - not:
                  - condition: state
                    entity_id: !input devices
                    attribute: volume_level
                    state: 0.2
            then:
              - service: media_player.volume_set
                entity_id: !input devices
                data:
                  volume_level: 0.2
      - conditions:
          - or:
              - "{{ activity_states in pct30 }}"
              - "{{ presence_states in pct30 }}"
              - "{{ time_states     in pct30 }}"
        sequence:
          - if:
              - not:
                  - condition: state
                    entity_id: !input devices
                    attribute: volume_level
                    state: 0.3
            then:
              - service: media_player.volume_set
                entity_id: !input devices
                data:
                  volume_level: 0.3
      - conditions:
          - or:
              - "{{ activity_states in pct40 }}"
              - "{{ presence_states in pct40 }}"
              - "{{ time_states     in pct40 }}"
        sequence:
          - if:
              - not:
                  - condition: state
                    entity_id: !input devices
                    attribute: volume_level
                    state: 0.4
            then:
              - service: media_player.volume_set
                entity_id: !input devices
                data:
                  volume_level: 0.4
      - conditions:
          - or:
              - "{{ activity_states in pct50 }}"
              - "{{ presence_states in pct50 }}"
              - "{{ time_states     in pct50 }}"
        sequence:
          - if:
              - not:
                  - condition: state
                    entity_id: !input devices
                    attribute: volume_level
                    state: 0.5
            then:
              - service: media_player.volume_set
                entity_id: !input devices
                data:
                  volume_level: 0.5
    default: []
mode: single
