blueprint:
  name: DEVICE Dehumidifier
  description: Manages a dehumidifier
  domain: automation
  source_url: https://github.com/konstar/hass/blob/main/blueprints/device-dehumidifier.yaml
  input:
    dehumidifier:
      name: Dehumidifier Activity Helper
      description: Helper which records the state of the dehumidifier
      selector:
        entity:
          domain: switch
          device_class: switch
    dehumidifier_activity:
      name: Dehumidifier Activity Helper
      description: Helper which records the state of the dehumidifier
      selector:
        entity:
          domain: input_select
    room_humidity:
      name: Humidity Sensor
      description: Sensor which records the humidity level of the room
      selector:
        entity:
          domain: sensor
          device_class: humidity
    room_door:
      name: Door Sensor
      description: Sensor which records the state of the door
      selector:
        entity:
          domain: binary_sensor
          device_class: door
variables:
  dehumidifer: !input dehumidifier
trigger:
  - id: maybe_full
    platform: state
    entity_id: !input dehumidifier_activity
    to: stopping
  - id: humid
    platform: numeric_state
    entity_id: !input room_humidity
    above: "60"
  - id: peak_on
    platform: state
    entity_id: input_boolean.electricity_rate_peak
    to: "on"
  - id: peak_off
    platform: state
    entity_id: input_boolean.electricity_rate_peak
    to: "off"
  - id: home_open
    platform: state
    entity_id: input_boolean.home_open
    for:
      minutes: 10
    to: "on"
  - id: home_closed
    platform: state
    entity_id: input_boolean.home_open
    to: "off"
    for:
      minutes: 1
  - id: door_closed
    platform: state
    entity_id: !input room_door
    to: "on"
  - id: door_open
    platform: state
    entity_id: !input room_door
    to: "off"
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: maybe_full
        sequence:
          - delay:
              hours: 0
              minutes: 10
              seconds: 0
              milliseconds: 0
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input dehumidifier_activity
                    state: sleeping
                sequence:
                  - service: script.notify
                    data:
                      message: "The Dehumidifier in the {{ area_name(dehumidifier) }} is full."
                      short_message: "{{ state_attr(dehumidifier,'friendly_name') }} is full"
              - conditions:
                  - condition: state
                    entity_id: !input dehumidifier_activity
                    state: stopping
                  - condition: numeric_state
                    entity_id: !input room_humidity
                    below: "55"
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: !input dehumidifier
                    data: {}
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: peak_on
              - condition: and
                conditions:
                  - condition: state
                    entity_id: input_boolean.home_open
                    state: "on"
                  - condition: state
                    entity_id: !input room_door
                    state: "off"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input dehumidifier
            data: {}
      - conditions:
          - condition: numeric_state
            entity_id: !input room_humidity
            above: "60"
          - condition: state
            entity_id: input_boolean.electricity_rate_peak
            state: "off"
          - condition: or
            conditions:
              - condition: state
                entity_id: input_boolean.home_open
                state: "off"
              - condition: and
                conditions:
                  - condition: state
                    entity_id: input_boolean.home_open
                    state: "on"
                  - condition: state
                    entity_id: !input room_door
                    state: "on"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input dehumidifier
            data: {}
    default: []
mode: single