blueprint:
  name: AREA Air Con
  description: Control vents for ducted air conditioner
  domain: automation
  source_url: https://github.com/konstar/hass/blob/main/blueprints/area-air-con.yaml
  input:
    air_con:
      name: Air Conditioner
      description: Air Conditioner of the room
      selector:
        entity:
          domain: climate
    door:
      name: Door
      description: Door sensor for the room
      selector:
        entity:
          domain: binary_sensor
          device_class: door
    activity:
      name: Activity Helper
      description: Activity helper of the room
      selector:
        entity:
          domain: input_select
    presence:
      name: Presence Helper
      description: Presence helper of the room
      selector:
        entity:
          domain: input_select
    humidity:
      name: Humidity Helper
      description: Humidity helper of the room
      selector:
        entity:
          domain: input_select
    temperature:
      name: Temperature Helper
      description: Temperature helper of the room
      selector:
        entity:
          domain: input_select
    temperature_sensor:
      name: Temperature Sensor
      description: Temperature sensor of the room
      selector:
        entity:
          domain: input_select
    temperature_target:
      name: Temperature Target Helper
      description: Target temperature helper of the room
      selector:
        entity:
          domain: input_number
variables:
  air_con: !input air_con
  door: !input door
  activity: !input activity
  presence: !input presence
  humidity: !input humidity
  temperature: !input temperature
  temperature_sensor: !input temperature_sensor
  temperature_target: !input temperature_target
trigger:
  - id: air_con_on
    platform: state
    entity_id: climate.home_air_con
    not_to: "off"
  - id: air_con_off
    platform: state
    entity_id: climate.home_air_con
    to: "off"
  - id: door_open
    platform: state
    entity_id: !input door
    to: "on"
  - id: door_closed
    platform: state
    entity_id: !input door
    to: "off"
  - platform: state
    entity_id: !input activity
  - platform: state
    entity_id: !input presence
  - platform: state
    entity_id: !input humidity
  - platform: state
    entity_id: !input temperature
  - platform: state
    entity_id: !input temperature_target
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: climate.home_air_con
            state: "off"
        sequence:
          - service: climate.set_temperature
            data:
              temperature: "{{ states(temperature_target)|round }}"
            target:
              entity_id: !input air_con
          - delay:
              minutes: 2
          - service: climate.turn_off
            target:
              entity_id: !input air_con
            data: {}
      - conditions:
          - condition: or
            conditions:
              - alias: Door open
                condition: state
                entity_id: !input door
                state: "on"
              - alias: Door closed and present
                condition: and
                conditions:
                  - condition: state
                    entity_id: !input door
                    state: "off"
                  - condition: state
                    entity_id: !input presence
                    state:
                      - enter
                      - present
              - condition: and
                conditions:
                  - condition: state
                    entity_id: !input presence
                    state:
                      - absent
                  - condition: or
                    conditions:
                      - condition: state
                        entity_id: !input temperature
                        state:
                          - very-hot
                      - condition: state
                        entity_id: !input humidity
                        state:
                          - very-humid
                          - humid
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: climate.home_air_con
                    state: fan_only
                sequence:
                  - service: climate.turn_on
                    target:
                      entity_id: !input air_con
                    data: {}
                  - service: climate.set_temperature
                    target:
                      entity_id: !input air_con
                    data:
                      temperature: "{{ states(temperature_target)|round }}"
                      hvac_mode: heat_cool
              - conditions:
                  - condition: state
                    entity_id: climate.home_air_con
                    state: heat
                sequence:
                  - if:
                      - condition: state
                        entity_id: !input temperature
                        state:
                          - normal
                          - cold
                          - very-cold
                    then:
                      - service: climate.turn_on
                        target:
                          entity_id: !input air_con
                        data: {}
                      - service: climate.set_temperature
                        target:
                          entity_id: !input air_con
                        data:
                          temperature: "{{ states(temperature_target)|round }}"
                          hvac_mode: heat_cool
                    else:
                      - service: climate.set_temperature
                        data:
                          temperature: "{{ states(temperature_target)|round }}"
                        target:
                          entity_id: !input air_con
                      - service: climate.turn_off
                        target:
                          entity_id: !input air_con
                        data: {}
              - conditions:
                  - condition: state
                    entity_id: climate.home_air_con
                    state: cool
                sequence:
                  - if:
                      - condition: state
                        entity_id: !input temperature
                        state:
                          - normal
                          - hot
                          - very-hot
                    then:
                      - service: climate.turn_on
                        target:
                          entity_id: !input air_con
                        data: {}
                      - service: climate.set_temperature
                        target:
                          entity_id: !input air_con
                        data:
                          temperature: "{{ states(temperature_target)|round }}"
                          hvac_mode: heat_cool
                    else:
                      - service: climate.set_temperature
                        data:
                          temperature: "{{ states(temperature_target)|round }}"
                        target:
                          entity_id: !input air_con
                      - service: climate.turn_off
                        target:
                          entity_id: !input air_con
                        data: {}
              - conditions:
                  - condition: state
                    entity_id: climate.home_air_con
                    state: dry
                sequence:
                  - choose:
                      - conditions:
                          - condition: state
                            entity_id: !input temperature
                            state:
                              - hot
                              - very-hot
                        sequence:
                          - service: climate.turn_on
                            target:
                              entity_id: !input air_con
                            data: {}
                          - service: climate.set_temperature
                            target:
                              entity_id: !input air_con
                            data:
                              temperature: "{{ states(temperature_target)|round }}"
                              hvac_mode: heat_cool
                      - conditions:
                          - condition: state
                            entity_id: !input humidity
                            state: normal
                        sequence:
                          - service: climate.set_temperature
                            target:
                              entity_id: !input air_con
                            data:
                              temperature: "{{ states(temperature_target)|round }}"
                          - service: climate.turn_off
                            target:
                              entity_id: !input air_con
                            data: {}
                      - conditions:
                          - condition: state
                            entity_id: !input humidity
                            state: humid
                        sequence:
                          - service: climate.turn_on
                            target:
                              entity_id: !input air_con
                            data: {}
                          - service: climate.set_temperature
                            target:
                              entity_id: !input air_con
                            data:
                              temperature: "{{ states(temperature_sensor)|round - 1 }}"
                              hvac_mode: heat_cool
                      - conditions:
                          - condition: state
                            entity_id: !input humidity
                            state: very-humid
                        sequence:
                          - service: climate.turn_on
                            target:
                              entity_id: !input air_con
                            data: {}
                          - service: climate.set_temperature
                            target:
                              entity_id: !input air_con
                            data:
                              temperature: "{{ states(temperature_sensor)|round - 2 }}"
                              hvac_mode: heat_cool
                    default:
                      - service: climate.set_temperature
                        data:
                          temperature: "{{ states(temperature_target)|round }}"
                        target:
                          entity_id: !input air_con
                      - delay:
                          minutes: 2
                      - service: climate.turn_off
                        target:
                          entity_id: !input air_con
                        data: {}
    default:
      - service: climate.set_temperature
        data:
          temperature: "{{ states(temperature_target)|round }}"
        target:
          entity_id: !input air_con
      - delay:
          minutes: 2
      - service: climate.turn_off
        target:
          entity_id: !input air_con
        data: {}
mode: single
