blueprint:
  name: DEVICE Dehumidifier
  description: Manages a dehumidifier
  domain: automation
  source_url: https://github.com/konstar/hass/blob/main/blueprints/DEVICE-Dehumidifier.yaml
  input:
    dehumidifier:
      name: Dehumidifier Switch
      description: Switch to turn on/off the dehumidifier
      selector:
        entity:
          domain: switch
          device_class: switch
          multiple: false
    dehumidifier_activity:
      name: Dehumidifier Activity Helper
      description: Helper which records the state of the dehumidifier
      selector:
        entity:
          domain: input_select
          multiple: false
    humidity:
      name: Humidity Helper
      description: Sensor which records the humidity level of the room
      selector:
        entity:
          domain: input_select
          multiple: false
    door:
      name: Door Helper
      description: Helper which records the state of the door
      selector:
        entity:
          domain: input_boolean
          multiple: false
variables:
  dehumidifier: !input dehumidifier
trigger:
- id: maybe_full
  platform: state
  entity_id: !input dehumidifier_activity
  to: stopping
- id: home_open
  platform: state
  entity_id: input_boolean.home_open
  for:
    minutes: 5
  to: 'on'
- id: home_closed
  platform: state
  entity_id: input_boolean.home_open
  to: 'off'
  for:
    minutes: 1
- id: door_closed
  platform: state
  entity_id: !input door
  to: 'on'
- id: door_open
  platform: state
  entity_id: !input door
  to: 'off'
- platform: state
  entity_id: !input humidity
- platform: state
  entity_id: !input humidity
  to: normal
  for:
    minutes: 10
- platform: state
  entity_id: input_select.electricity_rate
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: maybe_full
        sequence:
          - delay:
              minutes: 10
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input dehumidifier_activity
                    state: sleeping
                sequence:
                  - service: script.notify
                    data:
                      message: The Dehumidifier in the {{ area_name(dehumidifier) }} is full.
                      short_message: '{{ state_attr(dehumidifier,''friendly_name'') }} is full'
              - conditions:
                  - condition: state
                    entity_id: !input dehumidifier_activity
                    state: stopping
                  - condition: state
                    entity_id: !input humidity
                    state:
                      - normal
                      - dry
                      - very-dry
                      - extremely-dry
                sequence:
                  - repeat:
                      while:
                        - condition: state
                          entity_id: !input dehumidifier_activity
                          state: stopping
                        - condition: state
                          entity_id: !input humidity
                          state:
                            - normal
                            - dry
                            - very-dry
                            - extremely-dry
                        - not:
                            - condition: state
                              entity_id: !input dehumidifer
                              state: "off"
                      sequence:
                        - service: switch.turn_off
                          entity_id: !input dehumidifier
                        - delay:
                            minutes: 1
      - alias: Switch off the dehumidifier if the room is dry
        conditions:
          - condition: state
            entity_id: !input humidity
            state:
              - dry
              - very-dry
              - extremely-dry
        sequence:
          - repeat:
              while:
                - condition: state
                  entity_id: !input humidity
                  state:
                    - dry
                    - very-dry
                    - extremely-dry
                - not:
                    - condition: state
                      entity_id: !input dehumidifer
                      state: "off"
              sequence:
                - service: switch.turn_off
                  entity_id: !input dehumidifier
                - delay:
                    minutes: 1
      - alias: Switch off the dehumidifier if the room isn't humid
        conditions:
          - condition: state
            entity_id: !input humidity
            state: normal
            for:
              minutes: 10
        sequence:
          - repeat:
              while:
                - condition: state
                  entity_id: !input humidity
                  state:
                    - normal
                - not:
                    - condition: state
                      entity_id: !input dehumidifer
                      state: "off"
              sequence:
                - service: switch.turn_off
                  entity_id: !input dehumidifier
                - delay:
                    minutes: 1
      - alias: There's no point dehumidifying the room if the house is open and the door
          to the room is left open
        conditions:
        - condition: state
          entity_id: input_boolean.home_open
          state: 'on'
        - condition: state
          entity_id: !input door
          state: 'on'
        sequence:
          - repeat:
              while:
                - condition: state
                  entity_id: input_boolean.home_open
                  state: 'on'
                - condition: state
                  entity_id: !input door
                  state: 'on'
                - not:
                    - condition: state
                      entity_id: !input dehumidifer
                      state: "off"
              sequence:
                - service: switch.turn_off
                  entity_id: !input dehumidifier
                - delay:
                    minutes: 1
      - alias: Switch off the dehumidifier if we're in shoulder and it isn't very humid
        conditions:
        - condition: state
          entity_id: input_select.electricity_rate
          state:
            - shoulder
        - not:
            - condition: state
              entity_id: !input humidity
              state:
                - very-humid
                - extremely-humid
        sequence:
          - repeat:
              while:
                - condition: state
                  entity_id: input_select.electricity_rate
                  state:
                    - shoulder
                - not:
                    - condition: state
                      entity_id: !input humidity
                      state:
                        - very-humid
                        - extremely-humid
                - not:
                    - condition: state
                      entity_id: !input dehumidifer
                      state: "off"
              sequence:
                - service: switch.turn_off
                  entity_id: !input dehumidifier
                - delay:
                    minutes: 1
      - alias: Switch off the dehumidifier if it is peak and not extremely humid
        conditions:
          - condition: state
            entity_id: input_select.electricity_rate
            state:
              - peak
          - not:
              - condition: state
                entity_id: !input humidity
                state:
                  - extremely-humid
        sequence:
          - repeat:
              while:
                - condition: state
                  entity_id: input_select.electricity_rate
                  state:
                    - peak
                - not:
                    - condition: state
                      entity_id: !input humidity
                      state:
                        - extremely-humid
                - not:
                    - condition: state
                      entity_id: !input dehumidifer
                      state: "off"
              sequence:
                - service: switch.turn_off
                  entity_id: !input dehumidifier
                - delay:
                    minutes: 1
    default:
      - repeat:
          while:
            - not:
                - condition: state
                  entity_id: !input dehumidifer
                  state: "on"
          sequence:
            - service: switch.turn_on
              entity_id: !input dehumidifier
            - delay:
                minutes: 1
mode: single
