blueprint:
  name: DEVICE Dehumidifier (blue)
  description: Manages a dehumidifier
  domain: automation
  source_url: https://github.com/konstar/hass/blob/main/blueprints/DEVICE-Dehumidifier-blue.yaml
  input:
    dehumidifier:
      name: Dehumidifier
      description: Entity that controls the dehumidifier
      selector:
        entity:
          domain: fan
          multiple: false
    dehumidifier_activity:
      name: Dehumidifier Activity Helper
      description: Helper which records the state of the dehumidifier
      selector:
        entity:
          domain: input_select
          multiple: false
    mold:
      name: Mold Risk Index
      description: Sensor which records the mold risk level of the room
      selector:
        entity:
          domain: sensor
          multiple: false
    door:
      name: Door Helper
      description: Helper which records the state of the door
      selector:
        entity:
          domain: input_boolean
          multiple: false
variables:
  dehumidifier: !input dehumidifier
trigger:
- id: maybe_full
  platform: state
  entity_id: !input dehumidifier_activity
  to: stopping
- id: home_open
  platform: state
  entity_id: input_boolean.home_open
  for:
    minutes: 5
  to: 'on'
- id: home_closed
  platform: state
  entity_id: input_boolean.home_open
  to: 'off'
  for:
    minutes: 1
- id: door_closed
  platform: state
  entity_id: !input door
  to: 'on'
- id: door_open
  platform: state
  entity_id: !input door
  to: 'off'
- platform: numeric_state
  entity_id: !input mold
  above: 0.5
  for:
    minutes: 1
- platform: numeric_state
  entity_id: !input mold
  below: 0.5
  for:
    minutes: 5
- platform: state
  entity_id: input_select.electricity_rate
- platform: state
  entity_id:
    - input_boolean.electricity_exporting
    - input_boolean.electricity_price_spike
    - input_boolean.electricity_grid_connected
condition: []
action:
  - choose:
      - alias: Turn off the dehumidifer if an exceptional Electricity event is happening
        conditions:
            - or:
                - condition: state
                  entity_id: input_boolean.electricity_exporting
                  state: "on"
                - condition: state
                  entity_id: input_boolean.electricity_price_spike
                  state: "on"
                - condition: state
                  entity_id: input_boolean.electricity_grid_connected
                  state: "off"
        sequence:
          - service: fan.turn_off
            entity_id: !input dehumidifier
          - delay:
              minutes: 1
      - alias: Dehumidifer might be full or might be starting to stop
        conditions:
          - condition: trigger
            id: maybe_full
        sequence:
          - delay:
              minutes: 10
          - choose:
              - alias: Dehumidifier is full
                conditions:
                  - condition: state
                    entity_id: !input dehumidifier_activity
                    state: sleeping
                sequence:
                  - service: script.notify
                    data:
                      message: The Dehumidifier in the {{ area_name(dehumidifier) }} is full.
                      short_message: '{{ state_attr(dehumidifier,''friendly_name'') }} is full'
              - alias: Dehumidifier is stopping
                conditions:
                  - condition: state
                    entity_id: !input dehumidifier_activity
                    state: stopping
                  - condition: numeric_state
                    entity_id: !input mold
                    below: 0.5
                sequence:
                  - repeat:
                      while:
                        - condition: state
                          entity_id: !input dehumidifier_activity
                          state: stopping
                        - condition: numeric_state
                          entity_id: !input mold
                          below: 0.5
                        - not:
                            - condition: state
                              entity_id: !input dehumidifier
                              state: "off"
                      sequence:
                        - service: fan.turn_off
                          entity_id: !input dehumidifier
                        - delay:
                            minutes: 1
      - alias: Switch off the dehumidifier if the room doesn't have a risk of mold
        conditions:
          - condition: numeric_state
            entity_id: !input mold
            below: 0.5
        sequence:
          - repeat:
              while:
                - condition: numeric_state
                  entity_id: !input mold
                  below: 0.5
                - not:
                    - condition: state
                      entity_id: !input dehumidifier
                      state: "off"
              sequence:
                - service: fan.turn_off
                  entity_id: !input dehumidifier
                - delay:
                    minutes: 1
      - alias: There's no point dehumidifying the room if the house is open and the door
          to the room is left open
        conditions:
        - condition: state
          entity_id: input_boolean.home_open
          state: 'on'
        - condition: state
          entity_id: !input door
          state: 'on'
        sequence:
          - repeat:
              while:
                - condition: state
                  entity_id: input_boolean.home_open
                  state: 'on'
                - condition: state
                  entity_id: !input door
                  state: 'on'
                - not:
                    - condition: state
                      entity_id: !input dehumidifier
                      state: "off"
              sequence:
                - service: fan.turn_off
                  entity_id: !input dehumidifier
                - delay:
                    minutes: 1
      - alias: Switch off the dehumidifier if we're in shoulder and there is only a low risk of mold
        conditions:
        - condition: state
          entity_id: input_select.electricity_rate
          state:
            - shoulder
        - condition: numeric_state
          entity_id: !input mold
          below: 1.5
        sequence:
          - repeat:
              while:
                - condition: state
                  entity_id: input_select.electricity_rate
                  state:
                    - shoulder
                - condition: numeric_state
                  entity_id: !input mold
                  below: 1.5
                - not:
                    - condition: state
                      entity_id: !input dehumidifier
                      state: "off"
              sequence:
                - service: fan.turn_off
                  entity_id: !input dehumidifier
                - delay:
                    minutes: 1
      - alias: Switch off the dehumidifier if it is peak and not extremely humid
        conditions:
          - condition: state
            entity_id: input_select.electricity_rate
            state:
              - peak
          - condition: numeric_state
            entity_id: !input mold
            below: 2.5
        sequence:
          - repeat:
              while:
                - condition: state
                  entity_id: input_select.electricity_rate
                  state:
                    - peak
                - condition: numeric_state
                  entity_id: !input mold
                  below: 2.5
                - not:
                    - condition: state
                      entity_id: !input dehumidifier
                      state: "off"
              sequence:
                - service: fan.turn_off
                  entity_id: !input dehumidifier
                - delay:
                    minutes: 1
      - alias: Switch off the dehumidifier if we are offgrid
        conditions:
          - condition: state
            entity_id: input_select.electricity_rate
            state:
              - offgrid
        sequence:
          - repeat:
              while:
                - condition: state
                  entity_id: input_select.electricity_rate
                  state:
                    - offgrid
                - not:
                    - condition: state
                      entity_id: !input dehumidifier
                      state: "off"
              sequence:
                - service: fan.turn_off
                  entity_id: !input dehumidifier
                - delay:
                    minutes: 1
    default:
      - repeat:
          while:
            - not:
                - condition: state
                  entity_id: !input dehumidifier
                  state: "on"
          sequence:
            - service: fan.turn_on
              entity_id: !input dehumidifier
            - delay:
                minutes: 1
mode: restart
