blueprint:
  name: DEVICE Heater set summary
  description: Manages the summary info of the device for presentation in Lovelace
  domain: automation
  source_url: https://github.com/konstar/hass/blob/main/blueprints/DEVICE-Heater-set-summary.yaml
  input:
    heater:
      name: Heater
      description: Heater of the room
      selector:
        entity:
          domain: climate
    summary:
      name: Heater summary helper
      description: Summary helper for the Heater
      selector:
        entity:
          domain: input_text
variables:
  heater: !input heater
  summary: !input summary
trigger:
  - platform: state
    entity_id: !input heater
  - platform: state
    entity_id: !input heater
    attribute: hvac_action
condition: []
action:
  - service: input_text.set_value
    data:
      value: |-
        {% if is_state(heater,'off') -%}
          Off
        {% elif is_state(heater,'unavailable') -%}
          Unknown
        {%- else -%}
          {{ state_attr(heater,'hvac_action')|title }}
        {%- endif %}
    target:
      entity_id: !input summary
mode: restart