blueprint:
  name: PLUG set activity
  description: Set activity state for a switch.
  domain: automation
  source_url: https://github.com/konstar/hass/blob/main/blueprints/plug-set-activity.yaml
  input:
    power_switch:
      name: Power Switch
      description: Switch with an associated power sensor.
      selector:
        entity:
          domain: switch
    power_sensor:
      name: Power Sensor
      description: Power sensor related to the switch.
      selector:
        entity:
          domain: sensor
          device_class: power
    activity_input:
      name: Dropdown Helper
      description: Dropdown helper associated with the power switch and sensor.
      selector:
        entity:
          domain: input_select
trigger:
  - platform: state
    entity_id: !input "power_switch"
  - platform: numeric_state
    entity_id: !input "power_sensor"
    below: "5"
  - platform: numeric_state
    entity_id: !input "power_sensor"
    above: "5"
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input "power_switch"
            state: "off"
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input "activity_input"
            data:
              option: "off"
      - conditions:
          - condition: state
            entity_id: !input "power_switch"
            state: "on"
          - condition: numeric_state
            entity_id: !input "power_sensor"
            below: "5"
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input "activity_input"
            data:
              option: sleeping
      - conditions:
          - condition: state
            entity_id: !input "power_switch"
            state: "on"
          - condition: numeric_state
            entity_id: !input "power_sensor"
            above: "5"
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input "activity_input"
            data:
              option: working
    default:
      - service: input_select.select_option
        data:
          option: unknown
        target:
          entity_id: !input "activity_input"
mode: single
max_exceeded: silent